### ISSUE TITLE
Feature Discussion: Response Header Test

### ISSUE THREAD

**Issue by cdhunt** [StackExchange/httpunit#21]
I've started a project heavily inspired (basically copied) by **httpunit** that fills a couple of specific use cases I didn't feel could easily be implemented in Go.

[**httpunitPS**](https://github.com/cdhunt/httpunitPS)

I'm targeting feature parity including the TOML config syntax. One feature I've implemented that I think would be easy enough to add to **httpunit** would be response header validation. 

Here's an example of the config syntax I've added.

```toml
[[plan]]
  label = "google"
  url = "https://www.google.com"
  code = 200
  timeout = "0:0:10"
  [plan.headers]
  Server = "gws"
```
